config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'landing#index'
  
  get'/home' => 'home#index'


  resources :users

  resources :trips, only: [:index, :new, :create, :show, :destroy] do

    resources :trip_registrations, only: [:create]
  end

  resources :trip_registrations, only: [:update, :destroy]

  get '/my_trips' => 'users#user_trip_search'


  namespace :api, defaults: { format: :json } do
    resources :trips, only: [:index, :show]
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :departure, presence: true
  validates :destination, presence: true

  belongs_to :driver, class_name: "User", foreign_key: :user_id
  has_many :trip_registrations, dependent: :destroy
  has_many :passengers, class_name: "User", through: :trip_registrations

  default_scope { order('departure ASC') }

  def self.trip_find(date = Date.current)
    order("title ASC").where("created_at > ?", date).limit(10)
  end

  def regs
    p = { accepted:[] }
    p[:total] = trip_registrations.length
    trip_registrations.to_ary.each do |r|
      puts "p[r.status]=#{p[r.status]}"
      p[r.status.to_sym] ||= []
      p[r.status.to_sym] << r
    end
    return p
  end

  def self.later_this_month(date = Date.current)
    Trip.all.where("departure BETWEEN ? and ?", date.beginning_of_day, date.end_of_month).limit(8)
  end

  def self.most_popular
    Trip.joins(:trip_registrations).group("trips.id").order("COUNT (*) DESC ").limit(5).count
  end

end

app/controllers/api/trips_controller.rb
class Api::TripsController < ApplicationController

  def index
    @trips = Trip.where("departure >= :today", today: Time.now)
    render status: 200, json: @trips
  end

  def show
    @trip = Trip.find(params[:id])
    render status: 200, json: @trip
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authorize_user

  def index
    @trips = Trip.where("departure >= :today", today: Time.now)
    @next_trips = Trip.later_this_month 
  end

  def new
    @trip = current_user.trips.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.valid?
      @trip.save
      flash[:success] = "You have successfully created a trip, Better get training for your next project!"
      redirect_to trip_path(@trip)
    else
      flash[:danger] = "All fields need to be completed to create a trip."
      render :new
    end
  end

  def show
    unless current_user
      flash[:warning] = "Please sign up or log in to view this page."
      redirect_to new_user_registration_path
    end
    @trip = Trip.find(params[:id])
    @driver = @trip.driver

    @trip_registrations = @trip.trip_registrations

     # @whos_going = @trip.regs[:accepted].collect {|r| r.passenger } + @trip.driver

  end


  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    flash[:info] = "You have just deleted a trip."
    redirect_to trips_path
  end

  def trip_params
    params.require(:trip).permit(:title, :description, :latitude, :longitude, :departure, :destination)
  end

end

app/helpers/api/trips_helper.rb
module Api::TripsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_trip_passenger_item.html.erb
  <div class="col-xs-2 col-md-2">
    <a href="<%= user_path(registration.passenger) %>">
      <img src="<%= gravatar_image_url(registration.passenger.email, size:50) %>" width="50" height="50" style="border-radius: 100px;"/>
    </a>
  </div>

app/views/trips/_trip_user_item.html.erb
<li class="list-group-item">
  <div class="media">
    <div class="media-left">
      <a href="/users/<%= registration.passenger.id%>">
        <img class="media-object" src="<%= gravatar_image_url(registration.passenger.email, size:50) %>" width="50" height="50" style="border-radius: 100px;">
      </a> 
    </div>
    <div class="media-body registration-body">
      <% if registration.status == "pending" %>
        Status:  <span id="status<%= registration.id %>" class="registration-<%= registration.status %>"><%= registration.status %></span>
        <a href="javascript:void(0)" class="btn btn-default btn-xs btn-accept registration-process" data-status="accepted" data-confirm="Are you sure you want to accept this request?" data-registration-id="<%= registration.id %>">
          <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">
          <span class="registration-text">Accept</span>
          </span>
        </a>
        <a href="javascript:void(0)" class="btn btn-default btn-xs btn-decline registration-process" data-status="declined" data-confirm="Are you sure you want to decline this request?" data-registration-id="<%= registration.id %>" role="button">
          <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true">
          <span class="registration-text">Decline</span>
          </span>
        </a>
      <% else %>
        Status:  <span id="status<%= registration.id %>" class="registration-<%= registration.status %>"><%= registration.status %></span>
      <% end %>
    </div>
  </div>
</li>

app/views/trips/index.html.erb
<div class="page-header" style="margin-top: 0px; color:white;">
  <h1>Find a trip </h1>
</div>
  <div class="row">
    <div class="col-md-4">
<div>
<div class="panel panel-primary">
      <div class="panel-heading">Coming up</div>
      <div class="panel-body">
        
        
          <% @next_trips.each do |trip| %>

            <div class="media media-list">
              <div class="media-left">
                <a href="#">
                 <img class="media-object" src="<%= gravatar_image_url(trip.driver.email, size:50) %>" width="50" height="50" style="border-radius: 100px;">
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= link_to trip.title, trip_path(trip.id), class: "black" %></h4>
                <p style="color: gray;"><%= trip.departure.strftime("%a %b #{trip.departure.day.ordinalize}") %></p>
              </div>
            </div>
            <% end %>
        
      </div>
    </div>
  

</div>
    </div>
    <div class="col-md-8">
    <div class="panel panel-primary">
  <div class="panel-heading">Click on any marker to see more info about a trip.</div>
  <div class="panel-body">
      <div id="trip-list-map"></div>
    </div>
    
  </div>
</div>
  </div>


<script>$(document).ready(loadMap());</script>

app/views/trips/new.html.erb
    <div class="row" style="color:white;">
    <div class="col-md-6 col-xs-6">
      
        <h2>Plan your trip</h2>
        <%= form_for [@user, @trip] do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :destination %><br />
          <%= f.text_field :destination, class: "form-control" %><br />
        </div>

        <div class="form-group">
          <label>Search for your trip starting point below or just click on the map</label>
          <input id="address" type="text" class="form-control" placeholder="Where is your trip starting?">
          <br/>
  
          <button class="btn btn-primary btn-sm" id="submit" type="submit">Search</button>
        </div>
        <input type="hidden" name="trip[latitude]" id="latitude">
        <input type="hidden" name="trip[longitude]" id="longitude">
        <br/>
        
        <div class="form-group">
          <%= f.label :departure_date %><br />
          <%= f.date_select :departure, class: " form-control" %>
        </div>
        <br/>
        
        <div class="actions">
          <%= f.submit "Save my trip!", class: "btn btn-primary" %>
        </div>
        <% end %>
      
    </div> 
    <div class="col-md-6 col-xs-6">
    
    <div id="new-trip-map"></div>
    
  </div>

</div> 

<script>
  $(function () {
    google.maps.event.addDomListener(window, 'load', createTripInitializeMap);
  })
</script>
      

app/views/trips/show.html.erb
<div class="col-md-6 col-xs-6">
  <div class="panel panel-primary">
  <div class="panel-heading"><%= @trip.title %></div>
  <div class="panel-body">
    <p><%= @trip.description %></p>
    <p>Destination: <%= @trip.destination %></p>
    <p>Departure: <%= @trip.departure.strftime("%a %b #{@trip.departure.day.ordinalize}") %></p>
    <input type="hidden" data-id="<%= @trip.id %>" id="trip_id">
    <br/>

    <% if @trip.passengers.blank? %>
    <p>No passengers on this trip yet!</p>
    <% end %>
    
    <% if current_user.id == @trip.driver.id %>
    <ul class="list-group">
      <% @trip_registrations.each do |registration| %>
      <%= render "trips/trip_user_item", registration: registration %>
      <% end %>
    </ul>

    <%= link_to 'Delete trip', trip_path(@trip), method: 'Delete', class: "btn btn-primary btn-sm delete_button", data: { confirm: "Are you sure?" } %>

    <% else %>
    
      <% @trip.regs[:accepted].each do |registration| %>
      <%= render "trips/trip_passenger_item", registration: registration %>
      <% end %>

      <% if !current_user.on_trip?(@trip) %>
      <%= link_to 'Join trip', trip_trip_registrations_path(@trip), method: 'Post', class: "btn btn-primary btn-sm", style: "margin-left: 10px;", data: { confirm: "Are you sure?" } %>

      <% elsif %>
      <% current_user.trip_status(@trip) == ("pending") %>
      <h5>Your current request for this trip is pending. </h5>
      <% end %>
    
    <% end %>
  </div>
</div>

    
  
</div>
<div class="col-md-6 col-xs-6">
<div class="panel panel-default">
  <div class="panel-body">
  <div id="trip-map-container"></div>
</div>
  </div>
</div>
<script>$(document).ready(loadMap('trip-map-container'));</script>