config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'landing#index'
  
  get'/home' => 'home#index'


  resources :users

  resources :trips, only: [:index, :new, :create, :show, :destroy] do

    resources :trip_registrations, only: [:create]
  end

  resources :trip_registrations, only: [:update, :destroy]

  get '/my_trips' => 'users#user_trip_search'


  namespace :api, defaults: { format: :json } do
    resources :trips, only: [:index, :show]
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    if current_user.present?
      redirect_to home_path
    end
    @new_user_session = User.new
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_login.html.erb
<div class="modal fade" id="loginModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Log in</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="field">
            <%= f.label :email, class: "white" %><br />
            <%= f.email_field :email, autofocus: true, class: "inputs form-control" %>
          </div>
          <div class="field">
            <%= f.label :password, class: "white" %><br />
            <%= f.password_field :password, autocomplete: "off", class: "inputs form-control" %>
          </div>
          <% if devise_mapping.rememberable? -%>
            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me, class: "white" %>
            </div>
          <% end %>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Log in", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/landing/_signup.html.erb
<div class="modal fade" id="signupModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Sign up</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
          <div class="form-group">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true, class: "inputs form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, class: "inputs form-control" %>
          </div>
          <div class="form-group">
              <%= f.check_box :role, {}, "driver", "passenger" %>
              <%= f.label :role, "(Check this box if you are a driver only)" %>
          </div>
          <div class="form-group">
            <%= f.label :password %><em>(8 characters minimum)</em>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off" %>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Save!", class: "btn btn-primary" %>
        <% end %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/landing/index.html.erb
<div class="jumbotron" id="jumbotron" style="margin-top: 20px;">
  <h1 id="backdrop" style="border-top: solid black 1px; margin-bottom: 0px; padding-top: 30px;">Gri-gri</h1>
  <h2 id="backdrop" style="border-bottom: solid black 1px; margin-top: 0px; padding-bottom: 30px;">The perfect place to find a trip to the best climbing spots in Spain!</h2>
  
  <ul class="cb-slideshow">
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
  </ul>
  <div class="container landing">
    <a class="btn btn-primary btn-lg hvr-bounce-in" style="margin-right: 10px;" href="#" data-toggle="modal" data-target="#loginModal" role="button">Log in</a>
    <a class="btn btn-primary btn-lg hvr-bounce-in" style="margin-left: 10px;" href="#" data-toggle="modal" data-target="#signupModal" role="button">Sign up</a>
  </div>
</div>

<%= render "landing/login" %>

<%= render "landing/signup" %>