config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'landing#index'
  
  get'/home' => 'home#index'


  resources :users

  resources :trips, only: [:index, :new, :create, :show, :destroy] do

    resources :trip_registrations, only: [:create]
  end

  resources :trip_registrations, only: [:update, :destroy]

  get '/my_trips' => 'users#user_trip_search'


  namespace :api, defaults: { format: :json } do
    resources :trips, only: [:index, :show]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :current_password

  # validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validates_length_of :password, minimum: 8, maximum: 15, on: :update, allow_blank: true

  has_many :trips, dependent: :destroy
  has_many :trip_registrations, dependent: :destroy
  has_many :lifts, through: :trip_registrations, source: :trip
  

  def on_trip?(trip)
    self.trip_registrations.where(trip_id: trip.id).size > 0
  end

  def trip_status(trip)
    self.trip_registrations.find_by(trip_id: trip.id).status
    
  end

  def later_this_month(date = Date.current)
    self.trips.where("departure >= ?", date.end_of_month).limit(5)
  end

  def upcoming(date = Date.current)
    self.trips.where("departure >= ?", date).limit(2)
  end

  def soon(date = Date.current)
    self.lifts.where("departure >= ?", date).limit(2)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def create

  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      redirect_to user_path(@user)
      return
    end

    render :edit
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def user_trip_search
    @trips = current_user.trips
  end

  

  def user_params
    params.require(:user).permit(:bio, :email, :climbing_grade, :climbing_style, :favourite_spots, :role)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_user.html.erb
<div class="modal fade" id="editModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <h2>Edit <%= resource_name.to_s.humanize %></h2>
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= devise_error_messages! %>
        <div class="form-group">
          <%= f.email_field :email, autofocus: true, placeholder: "Email", class:"form-control" %>
        </div>
        <div class="form-group" rows="3">
          <%= f.text_area :bio, autofocus: true, placeholder: "Write about yourself here...", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_field :climbing_grade, autofocus: true, placeholder: "climbing grade", class:"form-control" %>
        </div>
        <div class="form-group" rows="2">
          <%= f.text_area :favourite_spots, autofocus: true, placeholder: "Your favourite climbing spots", class:"form-control" %>
        </div>
        <div class="form-group" rows="1">
          <%= f.text_area :climbing_style, autofocus: true, placeholder: "What's your climbing style?", class:"form-control" %>
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Update", class: "btn btn-primary edit_button" %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/users/_joined_trips.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">Trips I've joined</div>
    <div class="panel-body">
      <% if current_user.lifts.empty? %>
      <h4>You haven't joined a trip</h4>
      <a class="btn btn-primary btn-sm hvr-bounce-in" href="/trips" role="button">Find me a trip!</a>
      <% else %>
      <% current_user.lifts.each do |lift| %>
      <ul>
        <li style="list-style-type: none;"><%= link_to lift.title, trip_path(lift) %></li>
        <a href="/users/<%= lift.driver.id%>">
          <img class="media-object" src="<%= gravatar_image_url(lift.driver.email, size:50) %>" width="50" height="50">
        </a>The trip organiser
      </ul>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_planned_trips.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">Trips I've planned</div>
    <div class="panel-body">
      <% if current_user.trips.empty? %>
      <h4>You haven't planned any trips yet!</h4>
      <a class="btn btn-primary btn-sm hvr-bounce-in" href="/trips/new" role="button">Plan your own trip</a>
      <% else %>
      <% current_user.trips.each do |trip| %>
      <ul>
        <li style="list-style-type: none;"><%= link_to trip.title, trip_path(trip), class: "black-my-trips" %></li>
        <br/>
        <li style="list-style-type: none;">Passengers on this trip: <span class="badge my-trips"><%= trip.passengers.count %></span></li>
      </ul>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <span style="font-size: 26px; position: relative;"><%= @user.name %></span>
        <img src="<%= gravatar_image_url(@user.email, size:80) %>" width="80" height="80" style="border-radius:5px; border: solid 1px white; position: relative; float: right;">
      </div>
      <div class="panel-body">
        <h5>About me: </h5><p><%= @user.bio %></p>
      </div>
      <!-- List group -->
      <ul class="list-group">
        <li class="list-group-item"><h5>Climbing grade: </h5><%= @user.climbing_grade %></li>
        <li class="list-group-item"><h5>Favourite spots: </h5><%= @user.favourite_spots %></li>
        <li class="list-group-item"><h5>Climbing style: </h5><%= @user.climbing_style %></li>
        <li class="list-group-item"><h5>Email: </h5><%= @user.email %></li>
        <% if current_user.id == @user.id %>
        <li class="list-group-item"><a class="btn btn-primary btn-md hvr-bounce-in" href="#" data-toggle="modal" data-target="#editModal" role="button">Edit my profile</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<%= render "/users/edit_user" %>

app/views/users/user_trip_search.html.erb
<div class="row">
  <% if current_user.role == "driver" %>
    <%= render "users/planned_trips" %>
    <%= render "users/joined_trips" %>
  <% else %>
    <%= render "users/joined_trips" %>
  <% end %>
</div>