config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'landing#index'
  
  get'/home' => 'home#index'


  resources :users

  resources :trips, only: [:index, :new, :create, :show, :destroy] do

    resources :trip_registrations, only: [:create]
  end

  resources :trip_registrations, only: [:update, :destroy]

  get '/my_trips' => 'users#user_trip_search'


  namespace :api, defaults: { format: :json } do
    resources :trips, only: [:index, :show]
  end

end

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
      <%= content_tag :div, message, class: "alert alert-#{key}" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar-fixed-bottom footer">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="footer-link" href="#" data-toggle="modal" data-target="#welcomeModal">Tutorial</a>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navcolour">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="hvr-fade-left"><%= link_to 'Trips', trips_path %></li>
        <% if current_user.role == "driver" %>
        <li class="hvr-fade-left"><%= link_to 'Plan a trip', new_trip_path %></li>
        <% end %>
      </ul>
      
      <div class="col-md-3 col-md-offset-3" style="height:50px;">
       <ul class="nav navbar-nav">
        <li>
          <a href="/" style="padding-top:10px;">
            <img alt="Gri-gri" src="/assets/favicon.jpg" width="30" height="30" style="border-radius:2px;">
            <span style="font-size: 18px;">Gri-gri</span>
          </a>
        </li>
        <li class="hvr-fade-left"></li>
      </ul>
      </div>
      
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        
          <li>
             
              <a href="/users/<%= current_user.id %>" style="padding: 0px;"><img class="media-object" id="grav" src="<%= gravatar_image_url(current_user.email, size: 50) %>"></a>
            
          </li>
          <li class="hvr-fade-right"><%= link_to 'My trips', my_trips_path(@user) %></li>
          <li class="hvr-fade-right"><%= link_to 'Log out', destroy_user_session_path, method: 'DELETE' %></li>
          <% else %>
          <li class="hvr-fade-right"><%= link_to 'Log in', new_user_session_path %></li>
        </ul>
        <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gri-gri</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.jpg' %>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Ubuntu">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Vollkorn">
    <meta content="width=device-width, initial-scale=1" name="viewport">
  </head>
  <body>
  <% if current_user.present? %>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash_messages" %>
    
    <%= render "layouts/background_items" %>
    <%= render "layouts/footer" %>
    <% end %>
    <%= render "home/welcome_tutorial" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=#{GOOGLEMAPS}"></script>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>